
  Welcome <M:name>!!

  We are now running the Playground+ base code which you'll find has a
  multitude of features to make life on <T:name> much easier
  and more fun.

  If you have any questions, problems or need help with commands then
  please ask one of the staff.

                                                           ~ The Admin

---------------------------------------------------------------------------

